# Generated by Django 3.0.3 on 2020-03-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('Aadhar', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('mobileno', models.TextField(max_length=10)),
                ('aadhar', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='gtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='gender',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Aadhar',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='Newmem_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('mobileno', models.TextField(max_length=10)),
                ('aadhar', models.TextField(max_length=12)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.family')),
            ],
        ),
        migrations.CreateModel(
            name='distgrains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheat', models.IntegerField(max_length=2)),
                ('rice', models.IntegerField(max_length=2)),
                ('dal', models.IntegerField(max_length=2)),
                ('rokel', models.IntegerField(max_length=2)),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration.Newmem_reg')),
            ],
        ),
    ]
