# Generated by Django 3.0.3 on 2020-03-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0002_auto_20200324_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
