# Generated by Django 3.0.3 on 2020-03-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0003_delete_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_user',
        ),
    ]
