# Generated by Django 3.0.3 on 2020-03-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0005_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Aadhar',
        ),
        migrations.AddField(
            model_name='registration',
            name='aadhar',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
