# Generated by Django 3.0.3 on 2020-03-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0006_auto_20200324_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newmem_reg',
            old_name='aadhar',
            new_name='Aadhar',
        ),
    ]
