# Generated by Django 3.0.3 on 2020-03-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0007_auto_20200324_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newmem_reg',
            old_name='Aadhar',
            new_name='aadhar',
        ),
    ]
