# Generated by Django 3.0.3 on 2020-04-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0009_auto_20200324_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmem_reg',
            name='aadhar',
            field=models.IntegerField(max_length=12),
        ),
    ]
