# Generated by Django 3.0.3 on 2020-04-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0010_auto_20200410_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmem_reg',
            name='aadhar',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
