# Generated by Django 3.1.1 on 2020-09-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0014_auto_20200812_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newmem_reg',
            new_name='mem_reg',
        ),
    ]
