# Generated by Django 3.1.1 on 2020-09-22 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0015_auto_20200922_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distgrains',
            name='dt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mem_reg',
            name='aadhar',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mem_reg',
            name='mobileno',
            field=models.TextField(),
        ),
    ]
