# Generated by Django 3.1.1 on 2020-09-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0016_auto_20200922_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distgrains',
            old_name='guid',
            new_name='gid',
        ),
        migrations.RemoveField(
            model_name='distgrains',
            name='id3',
        ),
        migrations.AddField(
            model_name='mem_reg',
            name='a',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distgrains',
            name='dal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='distgrains',
            name='rice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='distgrains',
            name='wheat',
            field=models.IntegerField(),
        ),
    ]
