# Generated by Django 3.1.1 on 2020-09-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0017_auto_20200922_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='distgrains',
            name='idd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
